### ISSUE TITLE
using the osmx python library, is there a way to download an OSM .pbf file using a bounding box parameter?

### ISSUE THREAD

**Issue by d3netxer** [protomaps/OSMExpress#10]
this would be cool

**Comment by bdon** [comment]
This can be added, is there an advantage over using subprocess.call with the `osmx` binary though? Other than not needing to have the `osmx` binary?

**Comment by d3netxer** [comment]
No, I don't think so. I was thinking it may make it a little bit easier to use with Anaconda. Running 'pip install osmx' doesn't install the binary does it?

**Comment by bdon** [comment]
It doesn't. That may be tricky to accomplish because of OS differences, I did start uploading static. binaries here: https://github.com/protomaps/OSMExpress/releases
