### ISSUE TITLE
Query for multiple nodes, ways, or relations at once by ID

### ISSUE THREAD

**Issue by CloudNiner** [protomaps/OSMExpress#15]
It would be nice if I could query for multiple ids at once per osm element and then have the result piped to stdout in a common data format such as CSV or GeoJSON. Something like
```
osmx query ./database.osmx way 1001 1002 1234
// or
osmx query ./database.osmx way 1001,1002,1234
```

I'm not that familiar with C++ or these APIs but it looks like if I wanted to do that myself using the osmexpress headers in code I'd have to make one `getReader(id)` call for each node, way or relation element that I wanted to pull from the database. Is that correct or is there another API call I can use to return a List of results?

**Comment by bdon** [comment]
@CloudNiner that's correct. calling getReader(id) costs almost nothing. 

I think using the programmatic API is better than extending the command line API to handle multiple objects, it would be complicated to specify if you only wanted a subset of tags, or if you had more than several thousand IDs to look up. are you using Python? that may be more convenient to query the DB with, but will be slower than if you compile a C++ program against the headers

**Comment by CloudNiner** [comment]
👍 that makes sense -- we'll press forward with the programmatic API. Thanks again for the quick response!
