### ISSUE TITLE
Script to render examples/screenshot.png

### ISSUE THREAD

**Issue by nside** [protomaps/OSMExpress#33]
I'd be interested in that script if you want to publish it. Thanks

**Comment by bdon** [comment]
I actually made that in QGIS, but here's the C++ program to export a WKT TSV file of S2 cell geometries:

    #include <iostream>
    #include <vector>
    #include "s2/s2region_coverer.h"
    #include "s2/s2latlng.h"
    #include "s2/s2latlng_rect.h"
    #include "s2/s2polyline.h"
    #include "s2/s2loop.h"
    
    using namespace std;

    void print(int i, S2Cell &cell) {
  	    S2LatLng latlng{cell.GetVertex(i)};
  	    cout << latlng.lng() << " " << latlng.lat();
    }

    int main(int argc, char* argv[]) {
        ... define points ...
        auto c = std::make_unique<S2Polyline>(points);
        S2RegionCoverer::Options options;
	    options.set_max_cells(1024);
	    options.set_max_level(16);
	    S2RegionCoverer coverer{options};
  	    for (auto const &cell_id : coverer.GetCovering(*c)) {
		    S2Cell cell{cell_id};
          cout << cell.id().level() << "\t";
  		    cout << "POLYGON ((";
  		    for (int i = 0; i <= 3; i++) {
  			    print(i, cell);
  			    cout << ", ";
  		    }
  		    print(0,cell);
  		    cout << "))" << endl;
  	    }
    }
