### ISSUE TITLE
`make install` does not install osmx

### ISSUE THREAD

**Issue by Chaz6** [protomaps/OSMExpress#7]
After running  `cmake` and `make`, `make install` installs all files except for `osmx`.

**Comment by bdon** [comment]
Hi, I don't recommend running `make install` right now, you should be able to use the `osmx` binary that is created in the same directory as the CMakeLists.txt. 

To make this work correctly as the project matures, the `rpath`s for dynamically linked libraries need to be fixed, and I haven't been able to do this yet in a cross-platform way. It's also possible we can create a static binary, which would simplify this.

**Comment by bdon** [comment]
The static build should work now, and `make install` will default to installing `osmx` in /usr/local/bin. Let me know if this works for you.
